import = [
    "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"

#regular
size = 13
# offset.x = 0  # For letter spacing (default: 0)
# offset.y = 8  # For line spacing (default: 0)
