return {
	"williamboman/mason.nvim",
	opts = {
		ensure_installed = {
			"bash-language-server",
			"blade-formatter",
			"docker-compose-language-service",
			"dockerfile-language-server",
			"dot-language-server",
			"emmet-ls",
			"eslint_d",
			"hadolint",
			"html-lsp",
			"intelephense",
			"nginx-language-server",
			"chrome-debug-adapter",
			"php-debug-adapter",
			"phpcs",
			"php-cs-fixer",
			"phpstan",
			"pint",
			"prettier",
			"shellcheck",
			"shfmt",
			"stylua",
			"tailwindcss-language-server",
			"vtsls",
			"vue-language-server",
		},
	},
}
